coldict = {
    'KrHaus': 'Krankenhausaufnahme – Angabe, ob der Patient ins Krankenhaus aufgenommen wurde',
    'NA': 'Notarzt anwesend bei der Reanimation',
    'ROSC': 'Return of spontaneous circulation – Rückkehr eines eigenen Kreislaufs während oder nach der Reanimation',
    'KrCPR': 'Krankenhausaufnahme während laufender Reanimation',
    'KrROSC': 'Krankenhausaufnahme mit bereits erreichtem ROSC',
    '@24hÜ': 'Überleben nach 24 Stunden',
    'ENT30TÜ': 'Entlassung oder Überleben nach 30 Tagen',
    '@30TÜ': 'Überleben nach 30 Tagen',
    'ENT': 'Entlassungsstatus des Patienten',
    'CPC12': 'Cerebral Performance Category 1 oder 2 bei Entlassung – günstiges neurologisches Ergebnis',
    'CPC34': 'CPC 3 oder 4 bei Entlassung – ungünstiges neurologisches Ergebnis',
    'KoHDM': 'Zeitintervall vom Kollaps bis zur Herzdruckmassage (HDM) in Minuten:Sekunden',
    'AHDM': 'Zeitintervall vom Alarm bis zur Herzdruckmassage in Minuten:Sekunden',
    'A_ITN': 'Zeitintervall vom Alarm bis zur Intubation',
    'N_A_Ein1': 'Zeitintervall vom Notruf bis zum Eintreffen des ersten Rettungsmittels',
    'A_RTW': 'Zeitintervall Alarm bis Eintreffen Rettungswagen',
    'A_NEF': 'Zeitintervall Alarm bis Eintreffen Notarzteinsatzfahrzeug',
    'A_EIN1': 'Alarm bis Eintreffen 1. Fahrzeug [ ≤8min]',
    'A_NEF_A': 'Alarm bis Eintreffen NEF [≤8min]',
    'A_DEF1': 'Alarm bis erste Defibrillation',
    'A_VP1': 'Alarm bis Verabreichung der ersten Vasopressorgabe',
    'A_DEFVF': 'Alarm bis Defibrillation bei Vorliegen von Kammerflimmern (VF)',
    'A_VPASY': 'Alarm bis Vasopressorgabe bei Asystolie',
    'A_DVF': 'Defibrillation bei VF [≤8min]',
    'A_VP': 'Vasopressorgabe bei nicht VF [ ≤8min]',
    'AROSC': 'Alarm bis ROSC – Rückkehr des Spontankreislaufs',
    'A_Üb': 'Alarm bis Übergabe an das Krankenhaus',
    'A_Tod': 'Alarm bis Todesfeststellung',
    'D_CPR': 'Dauer der Reanimation von Alarm bis ROSC oder Tod (MM:SS)',
    'VFVT': 'Vorliegen von Kammerflimmern oder ventrikulärer Tachykardie',
    'AEMD': 'Vorliegen von pulsloser elektrischer Aktivität (PEA)',
    'Asy': 'Vorliegen von Asystolie',
    'kard': 'kardiale Ursache (vermutet)',
    'karU': 'kardiale oder unbekannte Ursache',
    'Hypox': 'hypoxische Ursache',
    'Trauma': 'traumatische Ursache',
    'Ertr': 'Ertrinken als vermutete Ursache',
    'noTBL': 'nicht traumatisch und keine Blutung als Ursache des Kreislaufstillstands',
    'Z_By': 'Zeuge des Kreislaufstillstands war ein Bystander',
    'Z_FR': 'Zeuge war ein First Responder',
    'Z_RD': 'Zeuge war der Rettungsdienst/Notarzt',
    'FR_CPR': 'Herzdruckmassage durch First Responder',
    'B_CPR': 'Herzdruckmassage durch Bystander (Laien)',
    'TCPR': 'Telefonisch angeleitete Herzdruckmassage (Telefon-CPR)',
    'VP': 'Verabreichung von Vasopressoren (z.B. Adrenalin)',
    'AMIO': 'Gabe von Amiodaron',
    'ATRO': 'Gabe von Atropin',
    'NABI': 'Gabe von Natriumbikarbonat',
    'Defi': 'Defibrillation durchgeführt',
    'L_Defi': 'Defibrillation durch Laien (nicht durch RD)',
    'N_Defi': 'Anzahl der Defibrillationen',
    'HHS': 'Gabe einer hypertonen NaCl-Lösung',
    'ITN': 'Endotracheale Intubation',
    'ITN_V': 'Intubation mit Video-Laryngoskopie',
    'SGA': 'Anwendung eines supraglottischen Atemwegshilfsmittels (SGA)',
    'nurSGA': 'Nur SGA verwendet, keine ITN',
    'AA_M': 'Advanced Airway (SGA oder ITN), insgesamt',
    'AA_BFR': 'Advanced Airway durch Bystander oder First Responder',
    'AA_RTW': 'Advanced Airway durch Rettungswagenbesatzung',
    'AA_NA': 'Advanced Airway durch Notarzt',
    'AIR_BE': 'Art des eingesetzten Atemwegshilfsmittels (Behrens-Kodierung)**',
    'ACCD': 'Mechanische Reanimationshilfe (z. B. Autopulse, Lucas, ACD-CPR)',
    'ManFeMasch': 'Art der Herzdruckmassage: manuell oder mit Gerät (Feedbacksystem)**',
    'IVZ': 'Zugang über intravenöse Gabe',
    'IOZ': 'Zugang über intraossäre Gabe',
    'ebAppl': 'Art der Medikamentenapplikation (iv, io, endobronchial etc.)',
    'ETIVIO': 'Kombinationen aus IV, IO, endotrachealer Gabe',
    'Alter': 'Alter in Jahren',
    'ageDB': 'Alter (aus Datenbank berechnet)**',
    'gt80J': 'Alter > 80 Jahre',
    '@1865J': 'Alter zwischen 18 und 65 Jahren',
    'lt18J': 'Alter < 18 Jahre',
    'ÖFFA': 'Kollaps in öffentlichem Raum oder Arztpraxis',
    'Whg': 'Kollaps in Wohnung',
    'male': 'Männliches Geschlecht',
    'RACA': 'RACA-Score – Prognostischer Score zur Überlebenswahrscheinlichkeit',
    'X': 'Unbekannt/Nicht spezifiziert**',
    'Lyse': 'Gabe einer Lysetherapie (z. B. bei Lungenembolie oder STEMI)',
    'MTH': 'Anwendung milder therapeutischer Hypothermie',
    'CORO': 'Durchgeführte Koronarangiographie',
    'RD_OUT': 'Out-of-Hospital Event durch Rettungsdienst**',
    'OUT_NEW': 'Out-of-Hospital Ereignis (neue Klassifikation)**',
    'REF_NA_IK': 'Referenz-Notarztstandort nach IK-Nummer**',
    'ORTK_INTIMC': 'Ort der Krankenhausaufnahme: Intermediate Care Station',
    'ORTK_OPAWR': 'Ort der Krankenhausaufnahme: OP-Aufwachraum',
    'ASS_HEP': 'Gabe von ASS (Aspirin) und/oder Heparin',
    'STEMI': 'ST-Hebungs-Myokardinfarkt als vermutete Ursache',
    'FEEDB': 'Verwendung eines CPR-Feedbacksystems während der Reanimation',
    'L_CPR': 'Durchführung einer CPR mit LUCAS-Gerät',
    'ACD_CPR': 'Aktive Kompression-Dekompression-CPR',
    'AP_CPR': 'CPR mit Autopulse-Gerät',
    'Lucas_CPR': 'CPR mit LUCAS-Gerät',
    'PES_K': 'Prä-Reanimations-Status: Klassifikation K**',
    'PES_101': 'Prä-Reanimations-Status nach Kodierung 101**',
    'AL_GR_cr': "Alarmsignalgruppe 'critical response'**",
    'i_ECG_cr': 'Initiales EKG mit kritisch auffälligem Befund**',
    'AD_GR_cr': 'Adrenalindosis Gruppe – kritisch relevant**',
    'PES_crass': 'Kombinierter präklinischer Risiko-Score (PES) – kritisch**',
    'E_ORT_crass': 'Einsatzort mit CRASS-Klassifikation**',
    'Stat_Ad_cr': 'Stationäre Aufnahme mit kritischem Befund**',
    'DCPRlt5_cr': 'Dauer der CPR < 5 Minuten, kritisch kodiert**',
    'K_CPR_cr': 'Komplexe CPR-Klassifikation**',
    'RF_INT': 'Risikofaktor: Intensivstationsaufnahme erforderlich',
    'BFRT_CPR': 'CPR durch Bystander mit Feedback-Rückmeldung**',
    'HF_GR': 'Herzfrequenz-Gruppe zum Zeitpunkt der Aufnahme**',
    'AltenH': 'Aufenthaltsort war ein Altenheim',
    'ORT_GUEN': 'Ort der Reanimation – Stadt/Gemeinde**',
    'CRASS_N': 'CRASS-Score (neurologische Prognose)**',
    'X_C': 'Nicht klassifizierte Kategorie C**',
    'CRASS_org': 'Original CRASS-Klassifikation des Falls**',
    'X_org': 'Nicht näher klassifizierte Originalkategorie**',
    'KAIR': 'Verabreichung von Medikamenten zur Atemwegssicherung (Künstliche Atemweg-Intervention)**',
    'ANÄ': 'Fachrichtung Anästhesiologie beteiligt**',
    'Jahr': 'Jahr der Reanimation oder Datensatzaufnahme',
    'RL_Quote': 'Quote der Reanimationen mit ROSC (Return of Spontaneous Circulation)**',
    'CPR_INZ': 'Inzidenzrate von Reanimationen pro Einwohner oder Zeitraum**',
    'CPC_Quote': 'Quote der günstigen neurologischen Outcomes (CPC 1–2)**',
    'Ü_SPo2': 'Sauerstoffsättigung bei Übergabe an Krankenhaus',
    'Ü_ETCO2': 'Endtidales CO2 bei Übergabe',
    'A_SPo2': 'Sauerstoffsättigung bei Ankunft im Krankenhaus',
    'A_ETCO2': 'Endtidales CO2 bei Ankunft im Krankenhaus',
    'PH': 'pH-Wert im Blut nach ROSC',
    'BE': 'Basenüberschuss/-defizit im Blut',
    'pCO2': 'Kohlendioxidpartialdruck im Blut',
    'LactatmmollNormlt2': 'Laktat-Konzentration (Norm < 2 mmol/l)',
    'BZ': 'Blutzucker',
    'Hypoxie': 'Hypoxie diagnostiziert (z. B. SpO2 < 90 %)',
    'Azidose': 'Metabolische Azidose diagnostiziert (z. B. pH < 7,2 und Laktat > 2)',
    'G_RFI': 'Globale Reanimations-Funktionsindikatoren (z. B. Score oder Bewertungssystem)**',
    'CORO_CPR': 'Koronarangiographie durchgeführt während CPR',
    'PCI': 'Perkutane Koronarintervention (Stent etc.) durchgeführt',
    'Lyse_KH': 'Lysebehandlung im Krankenhaus',
    'ECLS': 'Extracorporeal Life Support angewendet (ECMO etc.)',
    'Pacer_KH': 'Pacer-Therapie im Krankenhaus (z. B. transkutan oder intern)',
    'HITS_B': 'HITS-Behandlung – gezielte Hypothermie oder Neuroprotektion**',
    'Fieber_P': 'Fieberprävention oder -behandlung post-ROSC',
    'sek_KOMP': 'Sekundäre Komplikationen während Krankenhausverlauf',
    'TH_LIMIT': 'Therapielimitationen (z. B. DNR, Behandlungsabbruch)',
    'TageKrHaus': 'Anzahl der Tage im Krankenhaus bis Entlassung oder Tod',
    'Land': 'Bundesland des Einsatzortes (z. B. Bayern, Nordrhein-Westfalen)**',
    'PLZ': 'Postleitzahl des Einsatzortes**',
    'Kreis': 'Landkreis bzw. kreisfreie Stadt des Einsatzortes**',
    'DATUM': 'Datum der Reanimationsmaßnahmen (Beginn der Maßnahmen)',
    'STOKENN': 'Standortkennzeichen, vom Reanimationsregister vergeben',
    'EWZ': 'Einwohnerzahl im Versorgungsbereich des Notarztstandortes',
    'PATID': 'Patientenidentifikation zur Zuordnung und Anonymisierung',
    'PROTAR': 'Art des Einsatzes: 01=präklinisch, 02=innerklinisch',
    'GEBDAT': 'Geburtsdatum des Patienten, gespeichert als 01.Monat.Jahr',
    'ALT_CA': 'Wurde das Alter geschätzt? 01=Ja, 02=Nein',
    'PATALTER': 'Alter des Patienten im Format JJJ:MM (Jahre:Monate), berechnet aus Einsatz- und Geburtsdatum',
    'PATALTER_A': 'Jahre-Anteil des Patientenalters**',
    'PATALTER_B': 'Monate-Anteil des Patientenalters**',
    'PAEDALT': 'Altersgruppe Pädiatrie (<28 Tage): 01=1–7 Tage, 02=8–28 Tage',
    'GESCHL': 'Geschlecht des Patienten: 01=männlich, 02=weiblich',
    'PROTNR': 'Protokollnummer der Einsatzdokumentation oder Papierdokumentation',
    'RETTMIT1': 'Typ des eingesetzten Rettungsmittels: 01=Bodengebunden (RTW, NEF, NAW), 02=RTH/ITH',
    'NAMNEF': 'Kennung des Notarzteinsatzfahrzeugs (NEF), 999…=nicht bekannt',
    'REA1': 'Wurde eine Reanimation begonnen? 01=Ja durchgeführt; 02=Todes\xadfeststellung ohne Reanimation; 03=…',
    'PES': 'Zustand vor Notfall: 00=nicht dokumentiert; 01=ohne Vorerkrankung; …; 05=Patient stirbt innerhalb 24 h',
    'URKRSTST': 'Vermutete Ursache des Kreislaufstillstands: 01=kardial; 02=Trauma; …; 12=Sepsis; 99=nicht bekannt',
    'SPORT': 'Zusammenhang mit sportlicher Aktivität: 01=Ja; 02=Nein',
    'ZKOLL': 'Zeitpunkt des Kollapses (HH:MM), blank = nicht dokumentiert',
    'ZALFR': 'Alarmierungszeit des First Responders/Stationsteams (HH:MM)',
    'ZEPFR': 'Eintreffzeit des Stationsteams am Patienten (HH:MM)',
    'ZALARM': 'Alarmierungszeit des Rettungsdienstes/Notfallteams (HH:MM)',
    'ZEPN': 'Eintreffzeit des Notfallteams am Patienten (HH:MM)',
    'ZUEBG': 'Zeitpunkt der Übergabe an die weiterbehandelnde Einheit (HH:MM)',
    'ADATUM': 'Datum der Aufnahme ins Cardiac Arrest Center (TT.MM.JJJJ)',
    'ZADATUM': 'Uhrzeit der Aufnahme ins CAC (HH:MM)',
    'STOKENN_A': 'Standortkennung der weiterbehandelnden Klinik im CAC-Modul',
    'PATID_A': 'Patientenidentifikation im CAC-Modul',
    'GEBDAT_A': 'Geburtsdatum im CAC-Modul',
    'GESCHL_A': 'Geschlecht im CAC-Modul: 01=männlich, 02=weiblich',
    'PROTNR_A': 'Protokollnummer im CAC-Modul',
    'AUFNQ': 'Aufnahme von: 01=Präklinik, 02=Klinik**',
    'ZKUEBGP_A': 'Ort der Patientenübergabe im CAC-Modul**',
    'NAMKLIN_A': 'Zielklinik-Kürzel im CAC-Modul**',
    'IKNUMKLIN_A': 'IK-Nummer der Zielklinik im CAC-Modul**',
    'URKRSTST_A': 'Vermutete Ursache im CAC-Modul**',
    'EKG1_A': 'Erstbefund EKG bei Aufnahme im CAC-Modul**',
    'EINSAORT_CAC': 'Einsatzort-Code im CAC-Modul (Utstein-Style)**',
    'Azidose_grade': 'Schweregrad der metabolischen Azidose (z.\u2009B. leicht/mittel/schwer)**',
    'Azidose_schwer': 'Schwere Azidose – pH <\u20097,1 und Lactat deutlich erhöht**',
    'Azidose_lt7_1': 'pH <\u20097,1 – schwere metabolische Azidose**',
    'Azidose_lt6_9': 'pH <\u20096,9 – sehr schwere metabolische Azidose**',
    'VORERK_1': 'NA',
    'VORERK_2': 'NA',
    'VORERK_3': 'NA',
    'ZMELD': 'NA',
    'ZEOFR': 'NA',
    'ZALR': 'NA',
    'ZANKE_RD': 'NA',
    'ZEPR': 'NA',
    'ZTRAB': 'NA',
    'ZANKE_NA': 'NA',
    'EINSAORT': 'NA',
    'EOKC': 'NA',
    'EOKO': 'NA',
    'AUSBILD': 'NA',
    'FACH': 'NA',
    'EKG1': 'NA',
    'ATM1': 'NA',
    'BLUTZ1': 'NA',
    'TEMP1': 'NA',
    'ZCKB': 'NA',
    'ZCHDM': 'NA',
    'ZCATM': 'NA',
    'ZCDEFIAN': 'NA',
    'ZCDEFI': 'NA',
    'ZCSGA': 'NA',
    'ZCITN': 'NA',
    'ZCIV': 'NA',
    'ZCVP': 'NA',
    'ZCROSC1': 'NA',
    'ZKOLLAPS': 'NA',
    'ZHDM': 'NA',
    'ZATM': 'NA',
    'ZDEFIAN': 'NA',
    'ZDEFI1': 'NA',
    'ZSGA': 'NA',
    'ZINTUB': 'NA',
    'ZIV': 'NA',
    'ZEVP': 'NA',
    'ZROSC1': 'NA',
    'PACER': 'NA',
    'MTOCPR': 'NA',
    'ZVK': 'NA',
    'IOKAN': 'NA',
    'MTEB': 'NA',
    'TUBUS': 'NA',
    'MTAK': 'NA',
    'TYPAK_1': 'NA',
    'TYPAK_2': 'NA',
    'FBSYSTEM': 'NA',
    'TYPFBSYS': 'NA',
    'AUTOCPR': 'NA',
    'TYPAUCPR': 'NA',
    'NTECH': 'NA',
    'TYPNTECH_1': 'NA',
    'TYPNTECH_2': 'NA',
    'ADRENA': 'NA',
    'VASOPRE': 'NA',
    'ATROP': 'NA',
    'ZMMLYSE': 'NA',
    'NABIC': 'NA',
    'LIPID': 'NA',
    'AMIODA': 'NA',
    'MANALG1': 'NA',
    'HYPSED': 'NA',
    'IKOLL2': 'NA',
    'IKRIST2': 'NA',
    'SVR': 'NA',
    'MEDX_1': 'NA',
    'MEDX_2': 'NA',
    'TECHSCHO': 'NA',
    'ENERGIESCHO': 'NA',
    'ANZDEFI': 'NA',
    'DACTYP': 'NA',
    'DACTYP2': 'NA',
    'PAD': 'NA',
    'BEWLAG2': 'NA',
    'EKG2': 'NA',
    'ATM2_1': 'NA',
    'ATM2_2': 'NA',
    'GCS2': 'NA',
    'RRSYS2': 'NA',
    'UBDIA': 'NA',
    'HF2': 'NA',
    'AF2': 'NA',
    'BLUTZ2': 'NA',
    'UESAO': 'NA',
    'UECO': 'NA',
    'TEMP2': 'NA',
    'ROSC_A': 'NA',
    'KHAUF': 'NA',
    'ZTOD': 'NA',
    'NAMKLIN': 'NA',
    'IKNUMKLIN': 'NA',
    'KLIRANK': 'NA',
    'ZKUEBGP': 'NA',
    'KAIR_A': 'NA',
    'KVEN': 'NA',
    'NACHFNA': 'NA',
    'QMTEL': 'NA',
    'FREIGABEZEITPUNKT': 'NA',
    'LAND_A': 'NA',
    'QS_RFP': 'NA',
    'QS_RFP_HATRACA': 'NA',
    'QS_RFP_JEMALSROSC': 'NA',
    'QS_RFP_INZIDENZCPRBEGONNEN': 'NA',
    'QS_RFP_WVVORHANDENBEIKHAUFNAHME': 'NA',
    'QS_RFIR': 'NA',
    'QS_RFIR_JEMALSROSC': 'NA',
    'QS_RFIR_WVVORHANDENBEIKHAUFNAHME': 'NA',
    'RACA_A': 'NA',
    'V279': 'NA',
    'PROTAR_A': 'NA',
    'VERSION': 'NA',
    'DATUM_A': 'NA',
    'FALLNR': 'NA',
    'EOKO_A': 'NA',
    'EOKC_A': 'NA',
    'ZCKB_A': 'NA',
    'ZKOLL_A': 'NA',
    'ZCHDM_A': 'NA',
    'ZHDM_A': 'NA',
    'ROSC_B': 'NA',
    'ZROSC1_A': 'NA',
    'ADRENA_A': 'NA',
    'AMIODA_A': 'NA',
    'PES_A': 'NA',
    'AUTOCPR_A': 'NA',
    'BEWAUFN': 'NA',
    'ROSCA': 'NA',
    'EKGAUFN_1': 'NA',
    'EKGAUFN_2': 'NA',
    'EKGAUFN_3': 'NA',
    'RRAUFN': 'NA',
    'RRDAUFN': 'NA',
    'HFAUFN': 'NA',
    'AFAUFN': 'NA',
    'BEATAUFN': 'NA',
    'O2SAUFN': 'NA',
    'CO2AUFN': 'NA',
    'TEMPAUFN': 'NA',
    'BGAAUFN': 'NA',
    'HBAUFN': 'NA',
    'PHAUFN': 'NA',
    'BEAUFN': 'NA',
    'PCO2AUFN': 'NA',
    'LACTAUFN': 'NA',
    'BZAUFN': 'NA',
    'KREAAUFN': 'NA',
    'TROPART': 'NA',
    'TROPONW': 'NA',
    'TROPAAUFN': 'NA',
    'TROPAUFN': 'NA',
    'TROP2AAUFN': 'NA',
    'TROP2AUFN': 'NA',
    'BNPAUFN': 'NA',
    'REAVERL_1': 'NA',
    'REAVERL_2': 'NA',
    'REAVERL_3': 'NA',
    'REAVERL_4': 'NA',
    'REAVERL_5': 'NA',
    'REAVERL_6': 'NA',
    'URKRSTSTAUFN': 'NA',
    'ZROSCAUFN': 'NA',
    'EKG12': 'NA',
    'DEKG12': 'NA',
    'ZEKG12': 'NA',
    'EKG12AUF': 'NA',
    'STEMI_A': 'NA',
    'TEE': 'NA',
    'TTE': 'NA',
    'EFAST': 'NA',
    'CT': 'NA',
    'DCT': 'NA',
    'ZCT': 'NA',
    'CORO_A': 'NA',
    'DCORO': 'NA',
    'ZCORO': 'NA',
    'CORO_CPR_A': 'NA',
    'NCORO_GRUND': 'NA',
    'PCI_A': 'NA',
    'PCIERFOLG': 'NA',
    'PCIGEFAE_1': 'NA',
    'PCIGEFAE_2': 'NA',
    'PCIGEFAE_3': 'NA',
    'PCIGEFAE_4': 'NA',
    'LYSE_A': 'NA',
    'LYSE_ROSC_1': 'NA',
    'LYSE_ROSC_2': 'NA',
    'DLYSE': 'NA',
    'ZLYSE': 'NA',
    'ECLS_A': 'NA',
    'DECLS': 'NA',
    'ZECLS': 'NA',
    'IABP': 'NA',
    'DIABP': 'NA',
    'ZIABP': 'NA',
    'IMPELLA': 'NA',
    'DIMPELLA': 'NA',
    'ZIMPELLA': 'NA',
    'ACB': 'NA',
    'PACERWV': 'NA',
    'EPU': 'NA',
    'HITS_1': 'NA',
    'HITS_2': 'NA',
    'HITS_3': 'NA',
    'HITS_4': 'NA',
    'HITS_5': 'NA',
    'HITS_6': 'NA',
    'HITS_7': 'NA',
    'HITS_8': 'NA',
    'BZZIEL2': 'NA',
    'RRZIEL3': 'NA',
    'INSTAB_1': 'NA',
    'INSTAB_2': 'NA',
    'INSTAB_3': 'NA',
    'INSTAB_4': 'NA',
    'ECPRDBK': 'NA',
    'ECPRZBK': 'NA',
    'ECPRDST': 'NA',
    'ECPRZST': 'NA',
    'ECPRLACT': 'NA',
    'ECPRPH': 'NA',
    'ECPRBE': 'NA',
    'ECPRPCO2': 'NA',
    'ECPRPAO2': 'NA',
    'ECPRPUNKT': 'NA',
    'ECPRART': 'NA',
    'ECPRVEN_1': 'NA',
    'ECPRVEN_2': 'NA',
    'ECPRBEIN': 'NA',
    'ECPRVAV': 'NA',
    'ROSCECPR': 'NA',
    'ECPRENDE': 'NA',
    'ECPRKOMPL_1': 'NA',
    'ECPRKOMPL_2': 'NA',
    'ECPRKOMPL_3': 'NA',
    'ECPRKOMPL_4': 'NA',
    'ECPRDEND': 'NA',
    'ECPRZEND': 'NA',
    'ECLSIABP': 'NA',
    'IMPELLAECLS': 'NA',
    'AKTKUEHL': 'NA',
    'NAKTKUEHL_GRUND': 'NA',
    'KUEHLBEG': 'NA',
    'DKUEHLBEG': 'NA',
    'ZKUEHLBEG': 'NA',
    'DAUERKUEHL': 'NA',
    'ZIELTEMP1': 'NA',
    'DZIELTEMP': 'NA',
    'ZZIELTEMP': 'NA',
    'KUEHLREL': 'NA',
    'FIEB': 'NA',
    'FIEBPRAE': 'NA',
    'SSEP': 'NA',
    'NSE': 'NA',
    'EEGWV': 'NA',
    'CCT': 'NA',
    'CMRT': 'NA',
    'NEURO': 'NA',
    'LEB24H': 'NA',
    'LEB30D': 'NA',
    'KOMPLSEK_1': 'NA',
    'KOMPLSEK_2': 'NA',
    'KOMPLSEK_3': 'NA',
    'KOMPLSEK_4': 'NA',
    'KOMPLSEK_5': 'NA',
    'KOMPLSEK_6': 'NA',
    'KOMPLSEK_7': 'NA',
    'ICUTAGE': 'NA',
    'BEATSTD': 'NA',
    'ICDIMPL': 'NA',
    'LEBENTL': 'NA',
    'THLIMIT': 'NA',
    'GTHLIMIT_1': 'NA',
    'GTHLIMIT_2': 'NA',
    'GTHLIMIT_3': 'NA',
    'ORGANEXPL': 'NA',
    'ENTLDAT': 'NA',
    'DTOD': 'NA',
    'ZTOD_A': 'NA',
    'WVWIE': 'NA',
    'VDATUM': 'NA',
    'ZVDATUM': 'NA',
    'WVGRUND_1': 'NA',
    'WVGRUND_2': 'NA',
    'WVGRUND_3': 'NA',
    'WVGRUND_4': 'NA',
    'WVGRUND_5': 'NA',
    'WVGRUND_6': 'NA',
    'CPCENTL': 'NA',
    'MRSENTL': 'NA',
    'CPCVOR': 'NA',
    'MRSVOR': 'NA',
    'LEBENSQUAL1': 'NA',
    'EQ5D': 'NA',
    'SF12': 'NA',
    'LEB1JAHR': 'NA',
    'DTOD1JAHR': 'NA',
    'CPC1JAHR': 'NA',
    'CPC1JAHR_ERF': 'NA',
    'MRS1JAHR': 'NA',
    'MRS1JAHR_ERF': 'NA',
    'WOHNVOR': 'NA',
    'WOHNNACH': 'NA',
    'BERUF': 'NA',
    'FREIGABEZEITPUNKT_A': 'NA',
    'LAND_B': 'NA',
    'WV_TYP': 'NA',
    'filter_$': 'NA',
    'CPR_TOD': 'NA',
    'Hypoxie_grab': 'NA',
    'Azidose_grab': 'NA',
    'MaschCPR': 'NA',
    'Azidose_grad': 'NA',
}


{
    'VERSION': 'Version des DGAI-Reanimationsregister-Datensatzes Erstversorgung (aktuell Version 2.1)' :contentReference[oaicite:0]{index=0}&#8203;:contentReference[oaicite:1]{index=1},
    'ZMELD': 'Zeitpunkt des Absetzens bzw. Eingangs des Notrufs in der Rettungsleitstelle (Uhrzeit HH:MM)' :contentReference[oaicite:2]{index=2}&#8203;:contentReference[oaicite:3]{index=3},
    'ZALFR': 'Alarmierungszeit eines First-Responders als Vorausversorger neben dem regulären Rettungsdienst (Uhrzeit HH:MM)' :contentReference[oaicite:4]{index=4}&#8203;:contentReference[oaicite:5]{index=5},
    'ZEOFR': 'Eintreffzeit eines First-Responders am Einsatzort als Vorausversorger (Uhrzeit HH:MM)' :contentReference[oaicite:6]{index=6}&#8203;:contentReference[oaicite:7]{index=7},
    'ZEPFR': 'Eintreffzeit eines First-Responders am Patienten als Vorausversorger (Uhrzeit HH:MM)' :contentReference[oaicite:8]{index=8}&#8203;:contentReference[oaicite:9]{index=9},
    'ZALARM': 'Alarmierungszeit des Notarzteinsatzfahrzeugs (NEF) (Uhrzeit HH:MM)' :contentReference[oaicite:10]{index=10}&#8203;:contentReference[oaicite:11]{index=11},
    'ZANKE_NA': 'Eintreffzeit des Notarztes an der nächstgelegenen öffentlichen Straße zum Einsatzort (Uhrzeit HH:MM)' :contentReference[oaicite:12]{index=12}&#8203;:contentReference[oaicite:13]{index=13},
    'ZEPN': 'Eintreffzeit des Notarztes am Patienten (Uhrzeit HH:MM)' :contentReference[oaicite:14]{index=14}&#8203;:contentReference[oaicite:15]{index=15},
    'ZALR': 'Alarmierungszeit des Rettungswagens (RTW) (Uhrzeit HH:MM)' :contentReference[oaicite:16]{index=16}&#8203;:contentReference[oaicite:17]{index=17},
    'ZANKE_RD': 'Eintreffzeit des Rettungswagens an der nächstgelegenen öffentlichen Straße zum Einsatzort (Uhrzeit HH:MM)' :contentReference[oaicite:18]{index=18}&#8203;:contentReference[oaicite:19]{index=19},
    'ZEPR': 'Eintreffzeit des Rettungswagens am Patienten (Uhrzeit HH:MM)' :contentReference[oaicite:20]{index=20}&#8203;:contentReference[oaicite:21]{index=21},
    'ZTRAB': 'Beginn des Patiententransportes durch RTW/NEF in die Zielklinik (Uhrzeit HH:MM)' :contentReference[oaicite:22]{index=22}&#8203;:contentReference[oaicite:23]{index=23},
    'ZUEBG': 'Eintreffzeit des Patienten in der Zielklinik (Uhrzeit HH:MM)' :contentReference[oaicite:24]{index=24}&#8203;:contentReference[oaicite:25]{index=25},
    'EINSAORT': 'Einsatzort der Reanimation gemäß MIND3/Utstein-Style-Kodierung (z. B. 01=Wohnung, 06=Öffentlicher Raum etc.)' :contentReference[oaicite:26]{index=26}&#8203;:contentReference[oaicite:27]{index=27}
}
