# Liste aller gewünschten Keys
keys = [
    "KrHaus", "NA", "ROSC", "KrCPR", "KrROSC", "@24hÜ", "ENT30TÜ", "@30TÜ",
    "ENT", "CPC12", "CPC34", "KoHDM", "AHDM", "A_ITN", "N_A_Ein1", "A_RTW",
    "A_NEF", "A_EIN1", "A_NEF_A", "A_DEF1", "A_VP1", "A_DEFVF", "A_VPASY",
    "A_DVF", "A_VP", "AROSC", "A_Üb", "A_Tod", "D_CPR", "VFVT", "AEMD", "Asy",
    "kard", "karU", "Hypox", "Trauma", "Ertr", "noTBL", "Z_By", "Z_FR", "Z_RD",
    "FR_CPR", "B_CPR", "TCPR", "VP", "AMIO", "ATRO", "NABI", "Defi", "L_Defi",
    "N_Defi", "HHS", "ITN", "ITN_V", "SGA", "nurSGA", "AA_M", "AA_BFR", "AA_RTW",
    "AA_NA", "AIR_BE", "ACCD", "ManFeMasch", "IVZ", "IOZ", "ebAppl", "ETIVIO",
    "Alter", "ageDB", "gt80J", "@1865J", "lt18J", "ÖFFA", "Whg", "male", "RACA",
    "X", "Lyse", "MTH", "CORO", "RD_OUT", "OUT_NEW", "REF_NA_IK", "ORTK_INTIMC",
    "ORTK_OPAWR", "ASS_HEP", "STEMI", "FEEDB", "L_CPR", "ACD_CPR", "AP_CPR",
    "Lucas_CPR", "PES_K", "PES_101", "AL_GR_cr", "i_ECG_cr", "AD_GR_cr",
    "PES_crass", "E_ORT_crass", "Stat_Ad_cr", "DCPRlt5_cr", "K_CPR_cr",
    "RF_INT", "BFRT_CPR", "HF_GR", "AltenH", "ORT_GUEN", "CRASS_N", "X_C",
    "CRASS_org", "X_org", "KAIR", "ANÄ", "Jahr", "RL_Quote", "CPR_INZ",
    "CPC_Quote", "Ü_SPo2", "Ü_ETCO2", "A_SPo2", "A_ETCO2", "PH", "BE",
    "pCO2", "LactatmmollNormlt2", "BZ", "Hypoxie", "Azidose", "G_RFI",
    "CORO_CPR", "PCI", "Lyse_KH", "ECLS", "Pacer_KH", "HITS_B", "Fieber_P",
    "sek_KOMP", "TH_LIMIT", "TageKrHaus", "Land", "PLZ", "Kreis", "DATUM",
    "STOKENN", "EWZ", "PATID", "PROTAR", "GEBDAT", "ALT_CA", "P_ALTER",
    "PATALTER", "PATALTER_A", "PATALTER_B", "PAEDALT", "GESCHL", "PROTNR",
    "RETTMIT1", "NAMNEF", "REA1", "PES", "URKRSTST", "SPORT", "VORERK_1",
    "VORERK_2", "VORERK_3", "ZKOLL", "ZMELD", "ZALFR", "ZEOFR", "ZEPFR",
    "ZALR", "ZANKE_RD", "ZEPR", "ZTRAB", "ZUEBG", "ZALARM", "ZANKE_NA",
    "ZEPN", "EINSAORT", "EOKC", "EOKO", "AUSBILD", "FACH", "EKG1", "ATM1",
    "BLUTZ1", "TEMP1", "ZCKB", "ZCHDM", "ZCATM", "ZCDEFIAN", "ZCDEFI",
    "ZCSGA", "ZCITN", "ZCIV", "ZCVP", "ZCROSC1", "ZKOLLAPS", "ZHDM", "ZATM",
    "ZDEFIAN", "ZDEFI1", "ZSGA", "ZINTUB", "ZIV", "ZEVP", "ZROSC1", "PACER",
    "MTOCPR", "ZVK", "IOKAN", "MTEB", "TUBUS", "MTAK", "TYPAK_1", "TYPAK_2",
    "FBSYSTEM", "TYPFBSYS", "AUTOCPR", "TYPAUCPR", "NTECH", "TYPNTECH_1",
    "TYPNTECH_2", "ADRENA", "VASOPRE", "ATROP", "ZMMLYSE", "NABIC", "LIPID",
    "AMIODA", "MANALG1", "HYPSED", "IKOLL2", "IKRIST2", "SVR", "MEDX_1",
    "MEDX_2", "TECHSCHO", "ENERGIESCHO", "ANZDEFI", "DACTYP", "DACTYP2",
    "PAD", "BEWLAG2", "EKG2", "ATM2_1", "ATM2_2", "GCS2", "RRSYS2", "UBDIA",
    "HF2", "AF2", "BLUTZ2", "UESAO", "UECO", "TEMP2", "ROSC_A", "KHAUF",
    "ZTOD", "NAMKLIN", "IKNUMKLIN", "KLIRANK", "ZKUEBGP", "KAIR_A", "KVEN",
    "NACHFNA", "QMTEL", "FREIGABEZEITPUNKT", "LAND_A", "QS_RFP", 
    "QS_RFP_HATRACA", "QS_RFP_JEMALSROSC", "QS_RFP_INZIDENZCPRBEGONNEN",
    "QS_RFP_WVVORHANDENBEIKHAUFNAHME", "QS_RFIR", "QS_RFIR_JEMALSROSC",
    "QS_RFIR_WVVORHANDENBEIKHAUFNAHME", "RACA_A", "V279", "PROTAR_A",
    "VERSION", "DATUM_A", "ADATUM", "ZADATUM", "STOKENN_A", "PATID_A",
    "GEBDAT_A", "GESCHL_A", "PROTNR_A", "FALLNR", "AUFNQ", "ZKUEBGP_A",
    "NAMKLIN_A", "IKNUMKLIN_A", "URKRSTST_A", "EKG1_A", "EINSAORT_CAC",
    "EOKO_A", "EOKC_A", "ZCKB_A", "ZKOLL_A", "ZCHDM_A", "ZHDM_A", "ROSC_B",
    "ZROSC1_A", "ADRENA_A", "AMIODA_A", "PES_A", "AUTOCPR_A", "BEWAUFN",
    "ROSCA", "EKGAUFN_1", "EKGAUFN_2", "EKGAUFN_3", "RRAUFN", "RRDAUFN",
    "HFAUFN", "AFAUFN", "BEATAUFN", "O2SAUFN", "CO2AUFN", "TEMPAUFN",
    "BGAAUFN", "HBAUFN", "PHAUFN", "BEAUFN", "PCO2AUFN", "LACTAUFN",
    "BZAUFN", "KREAAUFN", "TROPART", "TROPONW", "TROPAAUFN", "TROPAUFN",
    "TROP2AAUFN", "TROP2AUFN", "BNPAUFN", "REAVERL_1", "REAVERL_2",
    "REAVERL_3", "REAVERL_4", "REAVERL_5", "REAVERL_6", "URKRSTSTAUFN",
    "ZROSCAUFN", "EKG12", "DEKG12", "ZEKG12", "EKG12AUF", "STEMI_A", "TEE",
    "TTE", "EFAST", "CT", "DCT", "ZCT", "CORO_A", "DCORO", "ZCORO", 
    "CORO_CPR_A", "NCORO_GRUND", "PCI_A", "PCIERFOLG", "PCIGEFAE_1",
    "PCIGEFAE_2", "PCIGEFAE_3", "PCIGEFAE_4", "LYSE_A", "LYSE_ROSC_1",
    "LYSE_ROSC_2", "DLYSE", "ZLYSE", "ECLS_A", "DECLS", "ZECLS", "IABP",
    "DIABP", "ZIABP", "IMPELLA", "DIMPELLA", "ZIMPELLA", "ACB", "PACERWV",
    "EPU", "HITS_1", "HITS_2", "HITS_3", "HITS_4", "HITS_5", "HITS_6",
    "HITS_7", "HITS_8", "BZZIEL2", "RRZIEL3", "INSTAB_1", "INSTAB_2",
    "INSTAB_3", "INSTAB_4", "ECPRDBK", "ECPRZBK", "ECPRDST", "ECPRZST",
    "ECPRLACT", "ECPRPH", "ECPRBE", "ECPRPCO2", "ECPRPAO2", "ECPRPUNKT",
    "ECPRART", "ECPRVEN_1", "ECPRVEN_2", "ECPRBEIN", "ECPRVAV", "ROSCECPR",
    "ECPRENDE", "ECPRKOMPL_1", "ECPRKOMPL_2", "ECPRKOMPL_3", "ECPRKOMPL_4",
    "ECPRDEND", "ECPRZEND", "ECLSIABP", "IMPELLAECLS", "AKTKUEHL",
    "NAKTKUEHL_GRUND", "KUEHLBEG", "DKUEHLBEG", "ZKUEHLBEG", "DAUERKUEHL",
    "ZIELTEMP1", "DZIELTEMP", "ZZIELTEMP", "KUEHLREL", "FIEB", "FIEBPRAE",
    "SSEP", "NSE", "EEGWV", "CCT", "CMRT", "NEURO", "LEB24H", "LEB30D",
    "KOMPLSEK_1", "KOMPLSEK_2", "KOMPLSEK_3", "KOMPLSEK_4", "KOMPLSEK_5",
    "KOMPLSEK_6", "KOMPLSEK_7", "ICUTAGE", "BEATSTD", "ICDIMPL", "LEBENTL",
    "THLIMIT", "GTHLIMIT_1", "GTHLIMIT_2", "GTHLIMIT_3", "ORGANEXPL",
    "ENTLDAT", "DTOD", "ZTOD_A", "WVWIE", "VDATUM", "ZVDATUM", "WVGRUND_1",
    "WVGRUND_2", "WVGRUND_3", "WVGRUND_4", "WVGRUND_5", "WVGRUND_6",
    "CPCENTL", "MRSENTL", "CPCVOR", "MRSVOR", "LEBENSQUAL1", "EQ5D",
    "SF12", "LEB1JAHR", "DTOD1JAHR", "CPC1JAHR", "CPC1JAHR_ERF",
    "MRS1JAHR", "MRS1JAHR_ERF", "WOHNVOR", "WOHNNACH", "BERUF",
    "FREIGABEZEITPUNKT_A", "LAND_B", "WV_TYP", "filter_$", "CPR_TOD",
    "Hypoxie_grab", "Azidose_grab", "MaschCPR", "Azidose_grad", "Azidose_schwer",
    "Azidose_lt7_1", "Azidose_lt6_9", "Azidose_grade"
]



# Dein bereits definiertes Dictionary mit Erklärungen
spalten_erlaeuterung = {
    "KrHaus": "Krankenhausaufnahme – Angabe, ob der Patient ins Krankenhaus aufgenommen wurde",
    "NA": "Notarzt anwesend bei der Reanimation",
    "ROSC": "Return of spontaneous circulation – Rückkehr eines eigenen Kreislaufs während oder nach der Reanimation",
    "KrCPR": "Krankenhausaufnahme während laufender Reanimation",
    "KrROSC": "Krankenhausaufnahme mit bereits erreichtem ROSC",
    "@24hÜ": "Überleben nach 24 Stunden",
    "ENT30TÜ": "Entlassung oder Überleben nach 30 Tagen",
    "@30TÜ": "Überleben nach 30 Tagen",
    "ENT": "Entlassungsstatus des Patienten",
    "CPC12": "Cerebral Performance Category 1 oder 2 bei Entlassung – günstiges neurologisches Ergebnis",
    "CPC34": "CPC 3 oder 4 bei Entlassung – ungünstiges neurologisches Ergebnis",
    "KoHDM": "Zeitintervall vom Kollaps bis zur Herzdruckmassage (HDM) in Minuten:Sekunden",
    "AHDM": "Zeitintervall vom Alarm bis zur Herzdruckmassage in Minuten:Sekunden",
    "A_ITN": "Zeitintervall vom Alarm bis zur Intubation",
    "N_A_Ein1": "Zeitintervall vom Notruf bis zum Eintreffen des ersten Rettungsmittels",
    "A_RTW": "Zeitintervall Alarm bis Eintreffen Rettungswagen",
    "A_NEF": "Zeitintervall Alarm bis Eintreffen Notarzteinsatzfahrzeug",
    "A_EIN1": "Alarm bis Eintreffen 1. Fahrzeug [ ≤8min]",
    "A_NEF_A": "Alarm bis Eintreffen NEF [≤8min]",
    "A_DEF1": "Alarm bis erste Defibrillation",
    "A_VP1": "Alarm bis Verabreichung der ersten Vasopressorgabe",
    "A_DEFVF": "Alarm bis Defibrillation bei Vorliegen von Kammerflimmern (VF)",
    "A_VPASY": "Alarm bis Vasopressorgabe bei Asystolie",
    "A_DVF": "Defibrillation bei VF [≤8min]",
    "A_VP": "Vasopressorgabe bei nicht VF [ ≤8min]",
    "AROSC": "Alarm bis ROSC – Rückkehr des Spontankreislaufs",
    "A_Üb": "Alarm bis Übergabe an das Krankenhaus",
    "A_Tod": "Alarm bis Todesfeststellung",
    "D_CPR": "Dauer der Reanimation = Zeit von Alarm bis ROSC oder Tod",
    "VFVT": "Vorliegen von Kammerflimmern oder ventrikulärer Tachykardie",
    "AEMD": "Vorliegen von pulsloser elektrischer Aktivität (PEA)",
    "Asy": "Vorliegen von Asystolie",
    "kard": "kardiale Ursache (vermutet)",
    "karU": "kardiale oder unbekannte Ursache",
    "Hypox": "hypoxische Ursache",
    "Trauma": "traumatische Ursache",
    "Ertr": "Ertrinken als vermutete Ursache",
    "noTBL": "nicht traumatisch und keine Blutung als Ursache des Kreislaufstillstands",
    "Z_By": "Zeuge des Kreislaufstillstands war ein Bystander",
    "Z_FR": "Zeuge war ein First Responder",
    "Z_RD": "Zeuge war der Rettungsdienst/Notarzt",
    "FR_CPR": "Herzdruckmassage durch First Responder",
    "B_CPR": "Herzdruckmassage durch Bystander (Laien)",
    "TCPR": "Telefonisch angeleitete Herzdruckmassage (Telefon-CPR)",
    "VP": "Verabreichung von Vasopressoren (z.B. Adrenalin)",
    "AMIO": "Gabe von Amiodaron",
    "ATRO": "Gabe von Atropin",
    "NABI": "Gabe von Natriumbikarbonat",
    "Defi": "Defibrillation durchgeführt",
    "L_Defi": "Defibrillation durch Laien (nicht durch RD)",
    "N_Defi": "Anzahl der Defibrillationen",
    "HHS": "Gabe einer hypertonen NaCl-Lösung",
    "ITN": "Endotracheale Intubation",
    "ITN_V": "Intubation mit Video-Laryngoskopie",
    "SGA": "Anwendung eines supraglottischen Atemwegshilfsmittels (SGA)",
    "nurSGA": "Nur SGA verwendet, keine ITN",
    "AA_M": "Advanced Airway (SGA oder ITN), insgesamt",
    "AA_BFR": "Advanced Airway durch Bystander oder First Responder",
    "AA_RTW": "Advanced Airway durch Rettungswagenbesatzung",
    "AA_NA": "Advanced Airway durch Notarzt",
    "AIR_BE": "Art des eingesetzten Atemwegshilfsmittels (Behrens-Kodierung)**",
    "ACCD": "Mechanische Reanimationshilfe (z. B. Autopulse, Lucas, ACD-CPR)",
    "ManFeMasch": "Art der Herzdruckmassage: manuell oder mit Gerät (Feedbacksystem)**",
    "IVZ": "Zugang über intravenöse Gabe",
    "IOZ": "Zugang über intraossäre Gabe",
    "ebAppl": "Art der Medikamentenapplikation (iv, io, endobronchial etc.)",
    "ETIVIO": "Kombinationen aus IV, IO, endotrachealer Gabe",
    "Alter": "Alter in Jahren",
    "ageDB": "Alter (aus Datenbank berechnet)**",
    "gt80J": "Alter > 80 Jahre",
    "@1865J": "Alter zwischen 18 und 65 Jahren",
    "lt18J": "Alter < 18 Jahre",
    "ÖFFA": "Kollaps in öffentlichem Raum oder Arztpraxis",
    "Whg": "Kollaps in Wohnung",
    "male": "Männliches Geschlecht",
    "RACA": "RACA-Score – Prognostischer Score zur Überlebenswahrscheinlichkeit",
    "X": "Unbekannt/Nicht spezifiziert**",
    "Lyse": "Gabe einer Lysetherapie (z. B. bei Lungenembolie oder STEMI)",
    "MTH": "Anwendung milder therapeutischer Hypothermie",
    "CORO": "Durchgeführte Koronarangiographie",
    "RD_OUT": "Out-of-Hospital Event durch Rettungsdienst**",
    "OUT_NEW": "Out-of-Hospital Ereignis (neue Klassifikation)**",
    "REF_NA_IK": "Referenz-Notarztstandort nach IK-Nummer**",
    "ORTK_INTIMC": "Ort der Krankenhausaufnahme: Intermediate Care Station",
    "ORTK_OPAWR": "Ort der Krankenhausaufnahme: OP-Aufwachraum",
    "ASS_HEP": "Gabe von ASS (Aspirin) und/oder Heparin",
    "STEMI": "ST-Hebungs-Myokardinfarkt als vermutete Ursache",
    "FEEDB": "Verwendung eines CPR-Feedbacksystems während der Reanimation",
    "L_CPR": "Durchführung einer CPR mit LUCAS-Gerät",
    "ACD_CPR": "Aktive Kompression-Dekompression-CPR",
    "AP_CPR": "CPR mit Autopulse-Gerät",
    "Lucas_CPR": "CPR mit LUCAS-Gerät",
    "PES_K": "Prä-Reanimations-Status: Klassifikation K**",
    "PES_101": "Prä-Reanimations-Status nach Kodierung 101**",
    "AL_GR_cr": "Alarmsignalgruppe 'critical response'**",
    "i_ECG_cr": "Initiales EKG mit kritisch auffälligem Befund**",
    "AD_GR_cr": "Adrenalindosis Gruppe – kritisch relevant**",
    "PES_crass": "Kombinierter präklinischer Risiko-Score (PES) – kritisch**",
    "E_ORT_crass": "Einsatzort mit CRASS-Klassifikation**",
    "Stat_Ad_cr": "Stationäre Aufnahme mit kritischem Befund**",
    "DCPRlt5_cr": "Dauer der CPR < 5 Minuten, kritisch kodiert**",
    "K_CPR_cr": "Komplexe CPR-Klassifikation**",
    "RF_INT": "Risikofaktor: Intensivstationsaufnahme erforderlich",
    "BFRT_CPR": "CPR durch Bystander mit Feedback-Rückmeldung**",
    "HF_GR": "Herzfrequenz-Gruppe zum Zeitpunkt der Aufnahme**",
    "AltenH": "Aufenthaltsort war ein Altenheim",
    "ORT_GUEN": "Ort der Reanimation – Stadt/Gemeinde**",
    "CRASS_N": "CRASS-Score (neurologische Prognose)**",
    "X_C": "Nicht klassifizierte Kategorie C**",
    "CRASS_org": "Original CRASS-Klassifikation des Falls**",
    "X_org": "Nicht näher klassifizierte Originalkategorie**",
    "KAIR": "Verabreichung von Medikamenten zur Atemwegssicherung (Künstliche Atemweg-Intervention)**",
    "ANÄ": "Fachrichtung Anästhesiologie beteiligt**",
    "Jahr": "Jahr der Reanimation oder Datensatzaufnahme",
    "RL_Quote": "Quote der Reanimationen mit ROSC (Return of Spontaneous Circulation)**",
    "CPR_INZ": "Inzidenzrate von Reanimationen pro Einwohner oder Zeitraum**",
    "CPC_Quote": "Quote der günstigen neurologischen Outcomes (CPC 1–2)**",
    "Ü_SPo2": "Sauerstoffsättigung bei Übergabe an Krankenhaus",
    "Ü_ETCO2": "Endtidales CO2 bei Übergabe",
    "A_SPo2": "Sauerstoffsättigung bei Ankunft im Krankenhaus",
    "A_ETCO2": "Endtidales CO2 bei Ankunft im Krankenhaus",
    "PH": "pH-Wert im Blut nach ROSC",
    "BE": "Basenüberschuss/-defizit im Blut",
    "pCO2": "Kohlendioxidpartialdruck im Blut",
    "LactatmmollNormlt2": "Laktat-Konzentration (Norm < 2 mmol/l)",
    "BZ": "Blutzucker",
    "Hypoxie": "Hypoxie diagnostiziert (z. B. SpO2 < 90 %)",
    "Azidose": "Metabolische Azidose diagnostiziert (z. B. pH < 7,2 und Laktat > 2)",
    "G_RFI": "Globale Reanimations-Funktionsindikatoren (z. B. Score oder Bewertungssystem)**",
    "CORO_CPR": "Koronarangiographie durchgeführt während CPR",
    "PCI": "Perkutane Koronarintervention (Stent etc.) durchgeführt",
    "Lyse_KH": "Lysebehandlung im Krankenhaus",
    "ECLS": "Extracorporeal Life Support angewendet (ECMO etc.)",
    "Pacer_KH": "Pacer-Therapie im Krankenhaus (z. B. transkutan oder intern)",
    "HITS_B": "HITS-Behandlung – gezielte Hypothermie oder Neuroprotektion**",
    "Fieber_P": "Fieberprävention oder -behandlung post-ROSC",
    "sek_KOMP": "Sekundäre Komplikationen während Krankenhausverlauf",
    "TH_LIMIT": "Therapielimitationen (z. B. DNR, Behandlungsabbruch)",
    "TageKrHaus": "Anzahl der Tage im Krankenhaus bis Entlassung oder Tod"
}

# Annahme: die Variable `keys` enthält weiterhin alle deine Feldnamen
# (wie im vorherigen Snippet)

# 1) erstelle ein Dictionary mit Default-Wert "NA"
my_dict = dict.fromkeys(keys, "NA")

# 2) überschreibe für alle Keys, für die eine Erklärung existiert
my_dict.update(spalten_erlaeuterung)

# Jetzt enthält `my_dict[key]` entweder die passende Erläuterung oder "NA"
print(my_dict)