spalten_erlaeuterung = {
    "KrHaus": "Krankenhausaufnahme – Angabe, ob der Patient ins Krankenhaus aufgenommen wurde",
    "NA": "Notarzt anwesend bei der Reanimation",
    "ROSC": "Return of spontaneous circulation – Rückkehr eines eigenen Kreislaufs während oder nach der Reanimation",
    "KrCPR": "Krankenhausaufnahme während laufender Reanimation",
    "KrROSC": "Krankenhausaufnahme mit bereits erreichtem ROSC",
    "@24hÜ": "Überleben nach 24 Stunden",
    "ENT30TÜ": "Entlassung oder Überleben nach 30 Tagen",
    "@30TÜ": "Überleben nach 30 Tagen",
    "ENT": "Entlassungsstatus des Patienten",
    "CPC12": "Cerebral Performance Category 1 oder 2 bei Entlassung – günstiges neurologisches Ergebnis",
    "CPC34": "CPC 3 oder 4 bei Entlassung – ungünstiges neurologisches Ergebnis",
    "KoHDM": "Zeitintervall vom Kollaps bis zur Herzdruckmassage (HDM) in Minuten:Sekunden",
    "AHDM": "Zeitintervall vom Alarm bis zur Herzdruckmassage in Minuten:Sekunden",
    "A_ITN": "Zeitintervall vom Alarm bis zur Intubation",
    "N_A_Ein1": "Zeitintervall vom Notruf bis zum Eintreffen des ersten Rettungsmittels",
    "A_RTW": "Zeitintervall Alarm bis Eintreffen Rettungswagen",
    "A_NEF": "Zeitintervall Alarm bis Eintreffen Notarzteinsatzfahrzeug",
    "A_EIN1": "Alarm bis Eintreffen 1. Fahrzeug [ ≤8min]",
    "A_NEF_A": "Alarm bis Eintreffen NEF [≤8min]",
    "A_DEF1": "Alarm bis erste Defibrillation",
    "A_VP1": "Alarm bis Verabreichung der ersten Vasopressorgabe",
    "A_DEFVF": "Alarm bis Defibrillation bei Vorliegen von Kammerflimmern (VF)",
    "A_VPASY": "Alarm bis Vasopressorgabe bei Asystolie",
    "A_DVF": "Defibrillation bei VF [≤8min]",
    "A_VP": "Vasopressorgabe bei nicht VF [ ≤8min]",
    "AROSC": "Alarm bis ROSC – Rückkehr des Spontankreislaufs",
    "A_Üb": "Alarm bis Übergabe an das Krankenhaus",
    "A_Tod": "Alarm bis Todesfeststellung",
    "D_CPR": "Dauer der Reanimation = Zeit von Alarm bis ROSC oder Tod",
    "VFVT": "Vorliegen von Kammerflimmern oder ventrikulärer Tachykardie",
    "AEMD": "Vorliegen von pulsloser elektrischer Aktivität (PEA)",
    "Asy": "Vorliegen von Asystolie",
    "kard": "kardiale Ursache (vermutet)",
    "karU": "kardiale oder unbekannte Ursache",
    "Hypox": "hypoxische Ursache",
    "Trauma": "traumatische Ursache",
    "Ertr": "Ertrinken als vermutete Ursache",
    "noTBL": "nicht traumatisch und keine Blutung als Ursache des Kreislaufstillstands",
    "Z_By": "Zeuge des Kreislaufstillstands war ein Bystander",
    "Z_FR": "Zeuge war ein First Responder",
    "Z_RD": "Zeuge war der Rettungsdienst/Notarzt",
    "FR_CPR": "Herzdruckmassage durch First Responder",
    "B_CPR": "Herzdruckmassage durch Bystander (Laien)",
    "TCPR": "Telefonisch angeleitete Herzdruckmassage (Telefon-CPR)",
    "VP": "Verabreichung von Vasopressoren (z.B. Adrenalin)",
    "AMIO": "Gabe von Amiodaron",
    "ATRO": "Gabe von Atropin",
    "NABI": "Gabe von Natriumbikarbonat",
    "Defi": "Defibrillation durchgeführt",
    "L_Defi": "Defibrillation durch Laien (nicht durch RD)",
    "N_Defi": "Anzahl der Defibrillationen",
    "HHS": "Gabe einer hypertonen NaCl-Lösung",
    "ITN": "Endotracheale Intubation",
    "ITN_V": "Intubation mit Video-Laryngoskopie",
    "SGA": "Anwendung eines supraglottischen Atemwegshilfsmittels (SGA)",
    "nurSGA": "Nur SGA verwendet, keine ITN",
    "AA_M": "Advanced Airway (SGA oder ITN), insgesamt",
    "AA_BFR": "Advanced Airway durch Bystander oder First Responder",
    "AA_RTW": "Advanced Airway durch Rettungswagenbesatzung",
    "AA_NA": "Advanced Airway durch Notarzt",
    "AIR_BE": "Art des eingesetzten Atemwegshilfsmittels (Behrens-Kodierung)**",
    "ACCD": "Mechanische Reanimationshilfe (z. B. Autopulse, Lucas, ACD-CPR)",
    "ManFeMasch": "Art der Herzdruckmassage: manuell oder mit Gerät (Feedbacksystem)**",
    "IVZ": "Zugang über intravenöse Gabe",
    "IOZ": "Zugang über intraossäre Gabe",
    "ebAppl": "Art der Medikamentenapplikation (iv, io, endobronchial etc.)",
    "ETIVIO": "Kombinationen aus IV, IO, endotrachealer Gabe",
    "Alter": "Alter in Jahren",
    "ageDB": "Alter (aus Datenbank berechnet)**",
    "gt80J": "Alter > 80 Jahre",
    "@1865J": "Alter zwischen 18 und 65 Jahren",
    "lt18J": "Alter < 18 Jahre",
    "ÖFFA": "Kollaps in öffentlichem Raum oder Arztpraxis",
    "Whg": "Kollaps in Wohnung",
    "male": "Männliches Geschlecht",
    "RACA": "RACA-Score – Prognostischer Score zur Überlebenswahrscheinlichkeit",
    "X": "Unbekannt/Nicht spezifiziert**",
    "Lyse": "Gabe einer Lysetherapie (z. B. bei Lungenembolie oder STEMI)",
    "MTH": "Anwendung milder therapeutischer Hypothermie",
    "CORO": "Durchgeführte Koronarangiographie",
    "RD_OUT": "Out-of-Hospital Event durch Rettungsdienst**",
    "OUT_NEW": "Out-of-Hospital Ereignis (neue Klassifikation)**",
    "REF_NA_IK": "Referenz-Notarztstandort nach IK-Nummer**",
    "ORTK_INTIMC": "Ort der Krankenhausaufnahme: Intermediate Care Station",
    "ORTK_OPAWR": "Ort der Krankenhausaufnahme: OP-Aufwachraum",
    "ASS_HEP": "Gabe von ASS (Aspirin) und/oder Heparin",
    "STEMI": "ST-Hebungs-Myokardinfarkt als vermutete Ursache",
    "FEEDB": "Verwendung eines CPR-Feedbacksystems während der Reanimation",
    "L_CPR": "Durchführung einer CPR mit LUCAS-Gerät",
    "ACD_CPR": "Aktive Kompression-Dekompression-CPR",
    "AP_CPR": "CPR mit Autopulse-Gerät",
    "Lucas_CPR": "CPR mit LUCAS-Gerät",
    "PES_K": "Prä-Reanimations-Status: Klassifikation K**",
    "PES_101": "Prä-Reanimations-Status nach Kodierung 101**",
    "AL_GR_cr": "Alarmsignalgruppe 'critical response'**",
    "i_ECG_cr": "Initiales EKG mit kritisch auffälligem Befund**",
    "AD_GR_cr": "Adrenalindosis Gruppe – kritisch relevant**",
    "PES_crass": "Kombinierter präklinischer Risiko-Score (PES) – kritisch**",
    "E_ORT_crass": "Einsatzort mit CRASS-Klassifikation**",
    "Stat_Ad_cr": "Stationäre Aufnahme mit kritischem Befund**",
    "DCPRlt5_cr": "Dauer der CPR < 5 Minuten, kritisch kodiert**",
    "K_CPR_cr": "Komplexe CPR-Klassifikation**",
    "RF_INT": "Risikofaktor: Intensivstationsaufnahme erforderlich",
    "BFRT_CPR": "CPR durch Bystander mit Feedback-Rückmeldung**",
    "HF_GR": "Herzfrequenz-Gruppe zum Zeitpunkt der Aufnahme**",
    "AltenH": "Aufenthaltsort war ein Altenheim",
    "ORT_GUEN": "Ort der Reanimation – Stadt/Gemeinde**",
    "CRASS_N": "CRASS-Score (neurologische Prognose)**",
    "X_C": "Nicht klassifizierte Kategorie C**",
    "CRASS_org": "Original CRASS-Klassifikation des Falls**",
    "X_org": "Nicht näher klassifizierte Originalkategorie**",
    "KAIR": "Verabreichung von Medikamenten zur Atemwegssicherung (Künstliche Atemweg-Intervention)**",
    "ANÄ": "Fachrichtung Anästhesiologie beteiligt**",
    "Jahr": "Jahr der Reanimation oder Datensatzaufnahme",
    "RL_Quote": "Quote der Reanimationen mit ROSC (Return of Spontaneous Circulation)**",
    "CPR_INZ": "Inzidenzrate von Reanimationen pro Einwohner oder Zeitraum**",
    "CPC_Quote": "Quote der günstigen neurologischen Outcomes (CPC 1–2)**",
    "Ü_SPo2": "Sauerstoffsättigung bei Übergabe an Krankenhaus",
    "Ü_ETCO2": "Endtidales CO2 bei Übergabe",
    "A_SPo2": "Sauerstoffsättigung bei Ankunft im Krankenhaus",
    "A_ETCO2": "Endtidales CO2 bei Ankunft im Krankenhaus",
    "PH": "pH-Wert im Blut nach ROSC",
    "BE": "Basenüberschuss/-defizit im Blut",
    "pCO2": "Kohlendioxidpartialdruck im Blut",
    "LactatmmollNormlt2": "Laktat-Konzentration (Norm < 2 mmol/l)",
    "BZ": "Blutzucker",
    "Hypoxie": "Hypoxie diagnostiziert (z. B. SpO2 < 90 %)",
    "Azidose": "Metabolische Azidose diagnostiziert (z. B. pH < 7,2 und Laktat > 2)",
    "G_RFI": "Globale Reanimations-Funktionsindikatoren (z. B. Score oder Bewertungssystem)**",
    "CORO_CPR": "Koronarangiographie durchgeführt während CPR",
    "PCI": "Perkutane Koronarintervention (Stent etc.) durchgeführt",
    "Lyse_KH": "Lysebehandlung im Krankenhaus",
    "ECLS": "Extracorporeal Life Support angewendet (ECMO etc.)",
    "Pacer_KH": "Pacer-Therapie im Krankenhaus (z. B. transkutan oder intern)",
    "HITS_B": "HITS-Behandlung – gezielte Hypothermie oder Neuroprotektion**",
    "Fieber_P": "Fieberprävention oder -behandlung post-ROSC",
    "sek_KOMP": "Sekundäre Komplikationen während Krankenhausverlauf",
    "TH_LIMIT": "Therapielimitationen (z. B. DNR, Behandlungsabbruch)",
    "TageKrHaus": "Anzahl der Tage im Krankenhaus bis Entlassung oder Tod"
}